<?php require('template/header.phtml') ?>
<link href="/clientserver/css/myStyle.css" rel="stylesheet">


<div class="text-center">
<form action="/clientserver/register.php" method="post" enctype="multipart/form-data">
    <div class="container">
        <h1>Register</h1>
        <p>Please fill in your details.</p>
        <hr>

        <div class="form-group">
        <label for="email"><b>Email</b></label>
        <input type="email" placeholder="Enter Email" name="email" id="email" required>
        </div>

        <div class="form-group">
        <label for="first_name"><b>First Name</b></label>
        <input type="text" placeholder="Enter First Name" name="first_name" id="first_name" required>
        </div>

        <div class="form-group">
        <label for="last_name"><b>Last Name</b></label>
        <input type="text" placeholder="Enter Last Name" name="last_name" id="last_name" required>
        </div>

        <div class="form-group">
        <label for="username"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="username" id="username" required>
        </div>

        <div class="form-group">
        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" id="psw" required>
        </div>

        <div class="form-group">
        <label for="psw-repeat"><b>Repeat Password</b></label>
        <input type="password" placeholder="Repeat Password" name="psw-repeat" id="psw-repeat" required>
        </div>

        <label for="img">Select image:</label>
        <div class="col-lg-offset-5">
        <div class="form-group">
        <input type="file" id="img" name="img" accept="image/*">
        </div>
        </div>
        <hr>

        <input type="checkbox" id="robotcheck" name="robotcheck" value="Human">
        <label for="robotcheck"> I am a human</label>


        <button type="submit" class="registerbtn">Register</button>
    </div>

    <div class="container signin">
        <p>Already have an account? <a href="login.php">Sign in</a>.</p>
    </div>
</form>


<?php require('template/footer.phtml') ?>
